name: CreateFramework
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get the versions
        id: get_version
        run: |
         echo ::set-output name=VERSION::${{ github.head_ref }}
      - name: Export to ios-spm repository
        uses: actions/github-script@master
        with:
          script: |
            console.log(${{ steps.get_version.outputs.VERSION }});
