name: CreateFramework
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: |
          echo "$GITHUB_REF"
