name: Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"


jobs:
  check-version:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
