name: CreateFramework
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: |
         echo ::set-output name=VERSION::${GITHUB_REF#refs/*/}
      - name: Export to ios-spm repository
        uses: actions/github-script@master
        with:
          script: |
            console.log(${{ steps.get_version.outputs.VERSION }});
