name: CreateFramework
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build XCFramework
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: |
         echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Update Pod File
        run: |
         
         sed -i '' 's/${GITHUB_REF/refs\/tags\//}/0.0.7/' ./TestCocoaPods_test_private.podspec
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git commit -m "Added framework"
          git push
