name: Release

on:
  push:
      branches:
      - 'master'

jobs:
   get-previous-tag:
    name: Test Get Previous Tag on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: 'Get Previous tag'
        id: previoustag
        uses: ./
      - run: |
          echo "${{ steps.previoustag.outputs.tag }}"
   
