name: CreateFramework
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build XCFramework
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tag number
        run : echo ${{ github.event.release.tag_name }}
