name: Release

on:
  push:
    tags:
      - "[0-9]"


jobs:
  check-version:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
          echo ${{ steps.get_version.outputs.VERSION }}
        
