name: Release

on:
  push:
    branches:    
      - 'master'

jobs:
   check-version:
    runs-on: macOS-11
    steps:
      - uses: actions/checkout@master
      - name: base_ref master
#        - name: Publish build(s) to Axiom
        shell: bash
        run: |
           chmod +x publish_to_axiom.sh
           bash publish_to_axiom.sh
           
      - name: set env
        run: echo “NOW=$(date +’%Y.%m.%d’)” >> $GITHUB_ENV

      - name: Create Tag
        run: |
          echo ${{ env.NOW }}
     #      git tag -a ${{ env.NOW }} -m "tag message"
      #    git push --tags
#         run: |
#           echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
#       - name: Update pod file
#         run: |
#           sed -i '' 's/0.0.7/${{ steps.get_version.outputs.VERSION }}/' ./TestCocoaPods_test_private.podspec
#       - name: Commit
#         run: |
#           # Stage the file, commit and push

#           git checkout master
#           git add .
#           git commit -m "Added framework"
#           git push origin master --force

   
